# Generated by Django 5.0.2 on 2024-02-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=10)),
                ('Description', models.TextField(max_length=500)),
            ],
        ),
    ]
