# Generated by Django 5.0.2 on 2024-02-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_education_program_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='Thingslearnt',
            field=models.TextField(max_length=200),
        ),
    ]
