# Generated by Django 5.0.2 on 2024-02-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_education_thingslearnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
