# Generated by Django 5.0.2 on 2024-02-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_projects_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='skills',
            new_name='programs',
        ),
        migrations.RenameModel(
            old_name='program',
            new_name='skill',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
