# Generated by Django 5.0.2 on 2024-02-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_rename_skills_programs_rename_program_skill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('date', models.TextField(max_length=10)),
                ('Description', models.TextField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='skill',
            new_name='skills',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
