# Generated by Django 5.0.2 on 2024-05-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_projects_rename_skill_skills_delete_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
