# Generated by Django 5.0.2 on 2024-05-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='duration',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
